### ISSUE TITLE
ImportError: No module named xml

### ISSUE THREAD

**Issue by andrey-pr** [leveldown-security/SVD-Loader-Ghidra#22]
Hello.
I get a problem when I try to launch script:
```
Traceback (most recent call last):
  File "/home/user/Ghidra-SVD-loader/SVD-Loader.py", line 14, in <module>
    from cmsis_svd.parser import SVDParser
  File "/home/user/Ghidra-SVD-loader/cmsis_svd/parser.py", line 16, in <module>
    from xml.etree import ElementTree as ET
ImportError: No module named xml
```
My configuration:
`Ubuntu 22.04`
`Ghidra 11.0`
`2.7.3 (tags/v2.7.3:5f29801fe, Sep 10 2022, 18:52:49)`
`[OpenJDK 64-Bit Server VM (Private Build)]`

It seems like python interpreter in ghidra have ho xml module, but according to docs it should.
Can you help me please to solve this problem?
Thank you

**Comment by andrey-pr** [comment]
Well, I solved my problem. Problem was in path to ghidra directory with cyrillic letters. Just place your ghidra on path only with ASCII letters and everything will be ok
